#Codici token
token.invito=I
token.psw=P
token.mfa=L

#Codici messaggi
msg.invitoUtentiInterni=RUI
msg.resetPassword=RP
msg.mfa=MFA
msg.invitoUtentiFornitori=RUF
msg.docInScadenza=DIS

#Applicazioni
app.ds=PortaleSubappaltatoriDataservice
app.web=PortaleSubappaltatoriWeb

#Scope
scope.admin=Amministratore
scope.responsabile=Responsabile
scope.gestione=Gestione
scope.consultazione=Consultazione
scope.fornitore=Fornitore
scope.passwordChange=password_change

#URL
url.web.base = http://localhost:8080/PortaleSubappaltatoriWeb/#/
pagina.invito = attivazione-utente/
pagina.psw = ripristino-password/

#Stato fornitore
statoFornitore.bozza=B
statoFornitore.invitato=I
statoFornitore.Registrato=R

#Tipo azione log
tipoAzioneLog.editTipoAllegato=Modificato tipo allegato
tipoAzioneLog.creatoTipoAllegato=Creato tipo allegato
tipoAzioneLog.addAllegatoTipoAzienda=Aggiunti allegati a tipo azienda
tipoAzioneLog.cancAllegatoTipoAzienda=Rimossi allegati a tipo azienda
tipoAzioneLog.salvatoFornitore=Fornitore Salvato
tipoAzioneLog.invitatoFornitore=Fornitore Invitato
tipoAzioneLog.fornitoreRegistrato=Fornitore registrato
tipoAzioneLog.inserimentoComunicazione=Comunicazione Inserita
tipoAzioneLog.modificaFornitore=Fornitore Modificato
tipoAzioneLog.inseritoTipoAllegatoPerFornitore=Inserito tipo allegato per fornitore
tipoAzioneLog.allegatoApprovato=Allegato Approvato
tipoAzioneLog.allegatoRigettato=Allegato Rigettato
tipoAzioneLog.caricatoAllegatoDaFornitore=Allegato caricato da Fornitore
tipoAzioneLog.utenteAttivato=Utente Attivato
tipoAzioneLog.utenteDisattivato=Utente Disattivato
tipoAzioneLog.referenteAggiunto=Aggiunto Referente
tipoAzioneLog.referenteModificato=Referente Modificato
tipoAzioneLog.documentoInviatoAfornitore=Documento inviato a fornitore
tipoAzioneLog.modificatoPersonale=Personale modificato
tipoAzioneLog.creatoPersonale=Personale creato
tipoAzioneLog.documentoInScadenza=Documento in scadenza
tipoAzioneLog.documentoStoricizzato=Documento storicizzato
tipoAzioneLog.documentoCondivisoImportato=Documento condiviso importato
tipoAzioneLog.fornitoreAggiuntoATenant=Fornitore aggiunto a Tenant

#Stato Allegato
statoAllegato.bozza=B
statoAllegato.inserito=I
statoAllegato.valutazione=V
statoAllegato.rigettato=R
statoAllegato.approvato=A
statoAllegato.visionato=MV
statoAllegato.annullato=X
statoAllegato.inScadenza=IS
statoAllegato.scaduto=S

#Macro tipologia
macroTipologia.aziendali=AZ
macroTipologia.personali=PE

#Tipologia
tipologia.moduli=MOD