#Codici token
token.invito=I
token.psw=P
token.mfa=L

#Codici messaggi
msg.invitoUtentiInterni=RUI
msg.resetPassword=RP
msg.mfa=MFA

#Applicazioni
app.ds=PortaleSubappaltatoriDataservice
app.web=PortaleSubappaltatoriWeb

#Scope
scope.admin=Amministratore
scope.responsabile=Responsabile
scope.gestione=Gestione
scope.consultazione=Consultazione
scope.fornitore=Fornitore
scope.passwordChange=password_change

#URL
url.web.base = http://localhost:8080/PortaleSubappaltatoriWeb/#/
pagina.invito = attivazione-utente/
pagina.psw = ripristino-password/

#Stato fornitore
statoFornitore.bozza=B
statoFornitore.invitato=I
statoFornitore.Registrato=R