#Codici token
token.invito=I
token.psw=P
token.mfa=L

#Codici messaggi
msg.invitoUtentiInterni=RUI
msg.resetPassword=RP
msg.mfa=MFA
msg.invitoUtentiFornitori=RUF

#Applicazioni
app.ds=PortaleSubappaltatoriDataservice
app.web=PortaleSubappaltatoriWeb

#Scope
scope.admin=Amministratore
scope.responsabile=Responsabile
scope.gestione=Gestione
scope.consultazione=Consultazione
scope.fornitore=Fornitore
scope.passwordChange=password_change

#URL
url.web.base = http://localhost:8080/PortaleSubappaltatoriWeb/#/
pagina.invito = attivazione-utente/
pagina.psw = ripristino-password/

#Stato fornitore
statoFornitore.bozza=B
statoFornitore.invitato=I
statoFornitore.Registrato=R

#Tipo azione log
tipoAzioneLog.editTipoAllegato=Modificato tipo allegato
tipoAzioneLog.creatoTipoAllegato=Creato tipo allegato
tipoAzioneLog.addAllegatoTipoAzienda=Aggiunti allegati a tipo azienda
tipoAzioneLog.cancAllegatoTipoAzienda=Rimossi allegati a tipo azienda
tipoAzioneLog.salvatoFornitore=Fornitore Salvato
tipoAzioneLog.invitatoFornitore=Fornitore Invitato
tipoAzioneLog.fornitoreRegistrato=Fornitore registrato
tipoAzioneLog.inserimentoComunicazione=Comunicazione Inserita
tipoAzioneLog.modificaFornitore=Fornitore Modificato